# Generated by Django 4.1.5 on 2023-01-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationname', models.CharField(max_length=100, null=True)),
                ('donationpic', models.FileField(null=True, upload_to='')),
                ('collectionloc', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('donationdate', models.DateTimeField(auto_now_add=True)),
                ('adminremark', models.CharField(max_length=300, null=True)),
                ('updationdate', models.DateTimeField(null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodwaste.donor')),
            ],
        ),
    ]
