# Generated by Django 4.1.5 on 2023-01-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0002_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='quality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
