# Generated by Django 4.1.5 on 2023-02-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0003_donation_quality_donation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donationcontact',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
